# Generated by Django 4.0 on 2021-12-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'permissions': (('can_view_discipline_page', 'View discipline page'),), 'verbose_name': 'Учебная дисциплина', 'verbose_name_plural': 'Учебные дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'permissions': (('can_view_lecturer_page', 'View lecturer page'),), 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='studygroup',
            options={'permissions': (('can_view_group_page', 'View study group page'),), 'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
    ]
